pageParam:
  in: query
  name: page
  description: current page number
  schema:
    type: integer
    format: int32
    example: 2
limitParam:
  in: query
  name: limit
  description: Number of items per page
  schema:
    type: integer
    format: int32
    example: 10
sortTypeParam:
  in: query
  name: sort_type
  description: The type of sort (asc or dsc)
  schema:
    type: string
    enum: [asc, dsc]
    example: dsc
sortByParam:
  in: query
  name: sort_by
  description: Sort key
  schema:
    type: string
    example: updatedAt
searchParam:
  in: query
  name: search
  description: Search term to filter restaurants by name and category
  schema:
    type: string
    example: title
filterParam:
  in: query
  name: filter
  description: Filter key
  schema:
    type: string
    example: category
idPathParam:
  in: path
  name: id
  description: Unique identifier
  required: true
  schema:
    type: string
    format: uuid
    example: 64b64c4f2f9b9c0012345678
